name: schedule

# Controls when the workflow will run
on:
  # 当push到main分支和定时时间时触发任务
  push:
    branches: [ main ]
  schedule:
    - cron: ' 0 1 * * *' # 东八区09:00，约莫有延时10~20，看github服务器情况

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 自动打卡任务
  autocard:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '17'

      - name: "Run AutoCard"
        run: cd action && java  --add-opens java.base/java.lang=ALL-UNNAMED -jar autocard-1.4.1.jar --app.autoCard.immediate=true
